version: '3.9'

services:
  db:
    image: 'postgres:14'
    environment:
      POSTGRES_USER: reportcreator
      POSTGRES_PASSWORD: reportcreator
      POSTGRES_DB: reportcreator
      PGDATA: /data
    volumes:
      - type: volume
        source: db-data
        target: /data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reportcreator"]
      interval: 2s
      timeout: 5s
      retries: 30
    restart: always
  languagetool:
    build: 
      context: ../languagetool
    init: true
    expose:
      - 8010
  app:
    build: 
      context: ../
    volumes:
      - type: volume
        source: app-data
        target: /data
    expose:
      - 8000
    ports:
      - 8000:8000
    environment:
      DATABASE_ENGINE: django.db.backends.postgresql
      DATABASE_HOST: db
      DATABASE_NAME: reportcreator
      DATABASE_USER: reportcreator
      DATABASE_PASSWORD: reportcreator
      SPELLCHECK_URL: http://languagetool:8010/
    env_file: app.env
    restart: always
    depends_on:
      db:
        condition: service_healthy
      languagetool:
        condition: service_started
        

volumes:
  db-data:
    name: reportcreator-db-data
  app-data:
    name: reportcreator-app-data
  nginx-certs:
    name: reportcreator-nginx-certs
