version: '3.9'

services:
  db:
    image: 'postgres:14'
    environment:
      POSTGRES_USER: reportcreator
      POSTGRES_PASSWORD: reportcreator
      POSTGRES_DB: reportcreator
      PGDATA: /data
    volumes:
      - type: volume
        source: db-data
        target: /data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reportcreator"]
      interval: 2s
      timeout: 5s
      retries: 30
    restart: always
    stop_grace_period: 120s
  languagetool:
    build: 
      context: ../languagetool
    init: true
    environment:
      languagetool_dbHost: db
      languagetool_dbName: reportcreator
      languagetool_dbUsername: reportcreator
      languagetool_dbPassword: reportcreator
    expose:
      - 8010
    healthcheck:
      test: ["CMD", "curl", "-f", "-so", "/dev/null", "http://localhost:8010/v2/languages"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
    restart: always
    depends_on:
      db: 
        condition: service_healthy
  app:
    build: 
      context: ../
    volumes:
      - type: volume
        source: app-data
        target: /data
    expose:
      - 8000
    ports:
      - 8000:8000
    environment:
      DATABASE_ENGINE: django.db.backends.postgresql
      DATABASE_HOST: db
      DATABASE_NAME: reportcreator
      DATABASE_USER: reportcreator
      DATABASE_PASSWORD: reportcreator
      SPELLCHECK_URL: http://languagetool:8010/
    env_file: app.env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/utils/healthcheck/"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
    depends_on:
      db:
        condition: service_healthy
      languagetool:
        condition: service_started
        

volumes:
  db-data:
    name: reportcreator-db-data
  app-data:
    name: reportcreator-app-data
